name = "Mercurium"
author = "BANanaDEV"
version = "0.9.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a559b97a4b79d284402d09ef922c3f0c3696749e54acef4ae3e629a66a89dd6c"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
